### ISSUE TITLE
Create Tests

### ISSUE THREAD

**Issue by CjKhaled** [CjKhaled/roost-frontend#15]
To make sure that we can verify functionality works, and still works through subsequent pushes, we need to start writing tests

### Tasks

- [x] Write tests for auth
- [x] Write tests for listings
- [ ] Write tests for menu

**Comment by CjKhaled** [comment]
i got this
