### ISSUE TITLE
Create A Home Page

### ISSUE THREAD

**Issue by CjKhaled** [CjKhaled/roost-frontend#18]
A user should still be able to use the app without having to log in. Create a home page that will allow a user to search for a city, state. It should link up with the Google Places API. From there, it should ask the backend for all the listings associated with that city, state.

### Tasks

- [ ] Refactor routes. Users should be able to access listings, listing, and home.
- [ ] The home page should be shown on first load.
- [ ] On the home page, it should call the places API and only allow city, state.

Create a new folder inside apps and call it home.
Put all components in /home/components
Put pages in /home/pages
Put tests in /home/tests
Put services (functions that call APIs) in /home/services
Put type declarations in /home/types.
Don't forget to add and import the routes.tsx file into the main router.

**Comment by CjKhaled** [comment]
I got this
