### ISSUE TITLE
Create Login Page

### ISSUE THREAD

**Issue by CjKhaled** [CjKhaled/roost-frontend#2]
This page will just display a form that will allow users to log into the system. Since the API is not connected yet, just submit to '#'. Would recommend designing how the page would look before hand in figma.

It should contain the following fields:

- Email
- Password

### Tasks

- [ ]  Create login page
- [ ]  Create a function that prints "Logging in..." in console, as well as what the user submitted. It should not reload the page.
- [ ]  Submit to '#'
- [ ] Adhere to our colors
- [ ] Validate form input (don't use the default validation, create your own with input validity)

Put the page in a file called Login.jsx /src/apps/auth/pages
Put components (such as reusable form inputs and form buttons in /src/apps/auth/components
Put relevant styles in /src/apps/auth/styles
