### ISSUE TITLE
Create Sign Up Page

### ISSUE THREAD

**Issue by CjKhaled** [CjKhaled/roost-frontend#3]
This page will just display a form that will allow users to sign into the system. Since the API is not connected yet, just submit to '#'. Would recommend designing how the page would look before hand in figma.

It should contain the following fields:

- First Name
- Last Name
- Email
- Password
- Confirm Password

### Tasks

- [ ]  Create form component
- [ ]  Create a function that prints "Signing up..." in console, as well as what the user submitted. It should not reload the page.
- [ ]  Submit to '#'
- [ ] Adhere to our colors
- [ ] Validate form input (don't use the default validation, create your own with input validity)

Put the page in a file called Signup.jsx /src/apps/auth/pages
Put components (such as reusable form inputs and form buttons in /src/apps/auth/components
Put relevant styles in /src/apps/auth/styles
