### ISSUE TITLE
Build Initial Design

### ISSUE THREAD

**Issue by CjKhaled** [CjKhaled/roost-frontend#4]
Use figma or something similar to figure out the general color scheme of the app. Take inspiration from any websites with a similar genre you see, or that generally look good.

### Tasks

- [ ] Pick a general color scheme, primary, secondary, accent, and neutral color
- [ ] Put these colors as variables in global.css
- [ ] Think of some layouts for the pages we need to create
- [ ] Configure headers in global.css
- [ ] Configure font styles in global.css
- [ ] Configure containers in global.css
